name: Build on Push

on:
  workflow_dispatch:
  push:
    branches:
    - msm-4.14-no-kp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3

    - name: Checkout zipper
      uses: actions/checkout@v3
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Arcturus
      with:
        arch: arm64
        compiler: aosp-clang/master/clang-r498229
        defconfig: x3_defconfig
        image: Image.gz-dtb

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        name: "Arcturus-X3-$(date '+%Y%m%d-%H%M').zip"
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
