name: Build with Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3
      
    - name: Docker Run Action
      uses: addnab/docker-run-action@v3
      with:
        image: ubuntu:jammy
        options: -v ${{ github.workspace }}:/src
        run: |
          sudo apt-get update
          ls
      
    - name: Artifact upload
      uses: actions/upload-artifact@v3.1.2
      with:
        name: output-dir
        path: ${{ github.workspace }}/Arcturus-*.zip
        if-no-files-found: ignore
