name: Build with Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3

    - name: Cache
      uses: actions/cache@v1.2.1
      with:
        path: ${{ github.workspace }}/proton-clang
        key: ${{ secrets.cache_key }}

    - name: Checkout toolchain
      uses: actions/checkout@v3
      with:
        repository: kdrag0n/proton-clang
        path: proton-clang
      
    - name: Docker Run Action
      uses: addnab/docker-run-action@v3
      with:
        image: ubuntu:jammy
        options: -v ${{ github.workspace }}:/src
        run: |
          apt-get update && apt-get install -y sudo
          sudo apt-get update
          sudo apt-get install -y git
          sudo apt-get install -y build-essential
          sudo apt-get install -y gcc binutils make
          ls
          echo "Changing directory to working directory"
          cd src
          ls
          chmod +x kernelbuilder.sh
          ./kernelbuilder.sh
      
    - name: Artifact upload
      uses: actions/upload-artifact@v3.1.2
      with:
        name: output-dir
        path: ${{ github.workspace }}/Arcturus-*.zip
        if-no-files-found: ignore
