name: Build on Push

on:
  workflow_dispatch:
  push:
    branches:
    - msm-4.14-no-kp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3

    - name: Checkout zipper
      uses: actions/checkout@v3
      with:
        repository: Aayu1254/AnyKernel3
        path: zipper
        
    - name: Get last tag
      id: last_tag
      uses: oprypin/find-latest-tag@v1
      continue-on-error: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        releases-only: true
        
    - name: Get next version code
      id: next_ver_code
      run: |
        TAG="${{ steps.last_tag.outputs.tag }}"
        if [ -z "$TAG" ]; then TAG=0; fi
        echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Arcturus
      with:
        arch: arm64
        compiler: aosp-clang/master/clang-r498229
        defconfig: x3_defconfig
        image: Image.gz-dtb
      
    - name: Artifact upload
      uses: actions/upload-artifact@v3
      with:
        name: output-kernel
        path: ${{ steps.build.outputs.outfile }}
        if-no-files-found: ignore
        
    - name: Artifact upload
      uses: actions/upload-artifact@v3
      with:
        name: output-dir
        path: /github/workspace/zipper/*
        if-no-files-found: ignore
        
    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.build.outputs.outfile }}
        release_name: Kernel
        tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
        file_glob: true
        overwrite: true
